"use client"
import './globals.css'
import { Inter } from 'next/font/google'
import { orbitron } from "./font";
import Navbar from "./component/Navbar";
import Footer from "./component/Footer";
import { Provider } from 'react-redux';
import {store} from "../app/Redux/store"
import { ThemeProvider } from "@material-tailwind/react";


const inter = Inter({ subsets: ['latin'] })

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={orbitron.variable}>
      <body className={inter.className}>
      <ThemeProvider>
      <Provider store={store}>
      
        <Navbar />
        {children}
        <Footer />
        </Provider>
        </ThemeProvider>
        </body>
    </html>
  )
}
