export const REGISTERE_REQUEST="REGISTERE_REQUEST";
export const REGISTERE_SUCCESS="REGISTERE_SUCCESS";
export const REGISTERE_FAILURE="REGISTERE_FAILURE";



export const LOGIN_REQUEST="LOGIN_REQUEST";
export const LOGIN_SUCCESS="LOGIN_SUCCESS";
export const LOGIN_FAILURE="LOGIN_FAILURE";